# Generated by Django 5.1 on 2024-09-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='selling_price',
            new_name='price',
        ),
    ]
