# Generated by Django 5.1 on 2024-09-02 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_rename_selling_price_trending_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom.product'),
        ),
    ]
