# Generated by Django 5.1 on 2024-09-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
