# Generated by Django 5.1 on 2024-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0009_rename_product_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
