# Generated by Django 5.1 on 2024-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0012_cart_add_at_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='area_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='primary_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='street_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
