# Generated by Django 5.1 on 2024-09-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0015_shipping_product_shipping_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(null=True)),
                ('expiry_month', models.CharField(max_length=20)),
                ('expiry_year', models.CharField(max_length=20)),
                ('CSC', models.IntegerField(null=True)),
            ],
        ),
    ]
