# Generated by Django 5.1 on 2024-09-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0017_alter_cart_quantity_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
